# Generated by Django 5.0.2 on 2024-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isdone',
            new_name='Isdone',
        ),
    ]
